version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai-mock-interview-db
    environment:
      POSTGRES_DB: ai_mock_interview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
